---
title: PrePostSex
timezone: UTC
collections:
  about:
    title: about
    output: true
  uploads:
    title: Uploads
    output: true
  prepostsex-entry:
    title: prepostsex-entry
    output: true
defaults:
- scope:
    path: ''
    type: prepostsex-entry
  values:
    title:
    image:
email: prepostsex@alune.fr
description: Something about a sex life.
baseurl:
url:
github_username: prepostsex
markdown: kramdown
plugins:
- jekyll-feed
